name: Zip and Dump Studies to S3

on:
  workflow_dispatch:

jobs:
  zip_and_s3_dump:
    if: github.repository == 'cbioportal/datahub'
    runs-on: ubuntu-latest
    env:
      SAML2AWS_VER: '2.36.18'
      AWS_PROFILE: 'default'
    steps:
      - name: Install saml2aws
        run: |
          wget -O saml2aws.tar.gz https://github.com/Versent/saml2aws/releases/download/v${SAML2AWS_VER}/saml2aws_${SAML2AWS_VER}_linux_amd64.tar.gz
          tar -xzvf saml2aws.tar.gz
          sudo mv saml2aws /usr/local/bin/
          chmod +x /usr/local/bin/saml2aws
          saml2aws --version
      - name: Configure saml2aws
        run: |
          saml2aws configure \
            --idp-provider="${{ secrets.SAML_IDP_PROVIDER }}"
            --mfa="${{ secrets.SAML_MFA }}"
            --url="${{ secrets.SAML_URL }}"
            --username="${{ secrets.SAML_USERNAME }}"
            --aws-urn="${{ secrets.SAML_AWS_URN }}"
            --session-duration="${{ secrets.SAML_SESSION_DURATION }}"
            --skip-verify="${{ secrets.SAML_SKIP_VERIFY }}"
            --skip-prompt \
            --profile="${{ env.AWS_PROFILE }}"
      - name: Login with saml2aws
        run: |
          echo "${{ secrets.SAML_PASSWORD }}" | saml2aws login \
            --force
            --skip-prompt
            --password-stdin
          aws --region us-east-1 s3 ls