name: Zip studies on push to master branch
on:
  # Trigger the workflow on push,
  # but only for the main branch
  push:
    branches:
      - zip-study-on-push-github-action
    paths:
      - 'public/**'
jobs:
  zip_studies:
    runs-on: ubuntu-latest
    steps:
    - id: files
      uses: jitterbit/get-changed-files@v1
    - run: | # TODO remove step
        echo ${{ steps.files.outputs.all }}
        exit 0
    - run: |
        echo "##[set-output name=unique_studies_list;]$(echo "${{ steps.files.outputs.all }}" | awk 'BEGIN { RS=" "; FS="/"; ORS=" " } { set[$2]++ } END { for (dir in set) { print dir } }')"
        exit 0
      id: unique_studies
    - run: | # TODO remove step
        echo ${{ steps.unique_studies.outputs.unique_studies_list }}
        exit 0
    - uses: actions/checkout@master
      with:
        lfs: 'true'
    - run: |
        mkdir studies_to_upload
        pwd
        ls -l
        cd public
        pwd
        ls -l
        for changed_study in ${{ steps.unique_studies.outputs.unique_studies_list }}; do
          echo "Compressing this study: ${changed_study}."
          tar -czvf ../studies_to_upload/${changed_study}.tar.gz ${changed_study}
        done
        ls -l
        cd ..
        pwd
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'studies_to_upload'      # optional: defaults to entire repository
