name: Zip studies on push to master branch
on:
  # Trigger the workflow on push,
  # but only for the master branch
  push:
    branches:
      - master
    paths:
      - 'public/**'
jobs:
  zip_studies:
    if: github.repository == 'cbioportal/datahub'
    runs-on: ubuntu-latest
    timeout-minutes: 1440
    steps:
    - id: files
      uses: jitterbit/get-changed-files@v1
    - run: |
        echo "##[set-output name=unique_studies_list;]$(echo "${{ steps.files.outputs.all }}" | awk 'BEGIN { RS=" "; FS="/"; ORS=" " } { set[$2]++ } END { for (dir in set) { print dir } }')"
        exit 0
      id: unique_studies
    - run: |
        git --version
        exit 0
    - uses: actions/checkout@v2
    - run: |
        # create a list of all studies under 'public'
        echo "[" > ${STUDY_LIST_FILENAME}
        for studypath in `find public -type d -depth 1`; do
          studyname=${studypath:7}
          echo "\"$studyname\"," >> ${STUDY_LIST_FILENAME}
        done
        echo "]" > ${STUDY_LIST_FILENAME}
        # copy study list file to S3
        aws s3 cp --acl public-read ${STUDY_LIST_FILENAME} s3://${AWS_S3_BUCKET}/
        echo study_list.json
        # first save .git
        tar -cvf ${SAVED_GIT_REPO_FILENAME} .git
        mkdir studies_to_upload
        cd public
        for changed_study in ${{ steps.unique_studies.outputs.unique_studies_list }}; do
          echo "Pulling study: ${changed_study}."
          git lfs pull --include="${changed_study}"
          echo "Compressing this study: ${changed_study}."
          tar -czvf ../studies_to_upload/${changed_study}.tar.gz ${changed_study}
          echo "Copy file to S3: ../studies_to_upload/${changed_study}.tar.gz"
          aws s3 cp --acl public-read ../studies_to_upload/${changed_study}.tar.gz s3://${AWS_S3_BUCKET}/
          echo "Remove this directory: ${changed_study}."
          rm -rf "${changed_study}"
          echo "Remove this file: ../studies_to_upload/${changed_study}.tar.gz."
          rm ../studies_to_upload/${changed_study}.tar.gz
          echo "Remove rm -rf .git"
          cd ..
          rm -rf .git
          # add original .git back
          tar -xf ${SAVED_GIT_REPO_FILENAME}
          cd public
        done
        cd ..
      env:
        STUDY_LIST_FILENAME: study_list.json
        SAVED_GIT_REPO_FILENAME: save_git.tar
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
